# Basic `dependabot.yml` file with
# minimum configuration for two package managers

version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "daily"
    assignees:
      - cedricziel
    groups:
       dev-dependencies:
          applies-to: version-updates # Applies the group rule to version updates
          patterns:
            - n8n-*

  # Enable version updates for Docker
  - package-ecosystem: "github-actions"
    # Look for a `Dockerfile` in the `root` directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
    assignees:
      - cedricziel
